/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

volatile uint8_t button_pressed = 0;

int main(void)
{
	volatile uint32_t *pRCC_AHB1ENR = (volatile uint32_t *)0x40023830;
    *pRCC_AHB1ENR = (1 << 2) | (1 << 0);

    volatile uint32_t *pRCC_APB2ENR = (volatile uint32_t *)0x40023844;
    *pRCC_APB2ENR = (1 << 14);

    volatile uint32_t *pGPIOC_MODER = (volatile uint32_t *)0x40020800;
    *pGPIOC_MODER &= ~(3U << 13 * 2);

    volatile uint32_t *pGPIOC_PUPDR = (volatile uint32_t *)0x4002080C;
    *pGPIOC_PUPDR &= ~(3U << 13 * 2);
    *pGPIOC_PUPDR |= (1U << 26);

    volatile uint32_t *pSYSCFG_EXTICR4 = (volatile uint32_t *)0x40013814;
    *pSYSCFG_EXTICR4 &= ~(0xFU << 4);
    *pSYSCFG_EXTICR4 |= (0x2U << 4);

    volatile uint32_t *pEXTI_FTSR = (volatile uint32_t *)0x40013C0C;
    *pEXTI_FTSR |= (1 << 13);

    volatile uint32_t *pEXTI_IMR = (volatile uint32_t *)0x40013C00;
    *pEXTI_IMR |= (1 << 13);


    volatile uint32_t *pNVIC_EnableIRQ = (volatile uint32_t *)0xE000E104;
    *pNVIC_EnableIRQ |= (1 << 8);

    volatile uint32_t *pGPIOA_MODER = (volatile uint32_t *)0x40020000;
    *pGPIOA_MODER &= ~(3U << 5 * 2);
    *pGPIOA_MODER |= (1 << 5 * 2);

	volatile uint32_t *pGPIOA_ODR = (volatile uint32_t *)0x40020014;


    while(1){

    	if(button_pressed == 1){

    		*pGPIOA_ODR ^= (1 << 5);
    		button_pressed = 0;
    	}

    }
}

    void EXTI15_10_IRQHandler(void){

    	volatile uint32_t *pEXTI_PR = (volatile uint32_t *)0x40013C14;
    	if(*pEXTI_PR & (1 << 13)){

    		*pEXTI_PR = (1 << 13);
    		button_pressed = 1;

    	}
}
