/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>

volatile uint8_t button_pressed = 0;
volatile uint16_t pot_value = 0;
volatile uint16_t previous_value = 0;

int update_pot_value(uint16_t new_reading){

	if(abs(new_reading - previous_value) > 5 ){

		previous_value = new_reading;

		return new_reading;
	}

	return previous_value;
}

int main(void)
{
	// RCC (Clock Synchronization)
	volatile uint32_t *pRCC_AHB1ENR = (volatile uint32_t *)0x40023830;
	volatile uint32_t *pRCC_APB2ENR = (volatile uint32_t *)0x40023844;

    *pRCC_AHB1ENR |= (1 << 2) | (1 << 0);
    *pRCC_APB2ENR |= (1 << 14) | (1 << 8);

    // GPIO Routing
    volatile uint32_t *pGPIOA_MODER = (volatile uint32_t *)0x40020000;
    volatile uint32_t *pGPIOC_MODER = (volatile uint32_t *)0x40020800;

     *pGPIOC_MODER &= ~(3U << 13 * 2);

     *pGPIOA_MODER &= ~(3U << 5 * 2);
     *pGPIOA_MODER |= (1 << 5 * 2);

     *pGPIOA_MODER |= (3U << 0);

    volatile uint32_t *pGPIOC_PUPDR = (volatile uint32_t *)0x4002080C;
    *pGPIOC_PUPDR &= ~(3U << 13 * 2);
    *pGPIOC_PUPDR |= (1U << 26);


    // SYSCFG (Interrupt Routing)
    volatile uint32_t *pSYSCFG_EXTICR4 = (volatile uint32_t *)0x40013814;
    *pSYSCFG_EXTICR4 &= ~(0xFU << 4);
    *pSYSCFG_EXTICR4 |= (0x2U << 4);

    //External Interrupt
    volatile uint32_t *pEXTI_FTSR = (volatile uint32_t *)0x40013C0C;
    volatile uint32_t *pEXTI_IMR = (volatile uint32_t *)0x40013C00;

    *pEXTI_FTSR |= (1 << 13);
    *pEXTI_IMR |= (1 << 13);

    //NIVC
    volatile uint32_t *pNVIC_EnableIRQ = (volatile uint32_t *)0xE000E104;
    volatile uint32_t *pNVIC_ISER0 = (volatile uint32_t *)0xE000E100;

    *pNVIC_EnableIRQ |= (1 << 8);

     // IRQ 18 (ADC Global Interrupt)
     *pNVIC_ISER0 |= (1U << 18);


    //ADC configuration
    volatile uint32_t *pADC_CR2 = (volatile uint32_t *)0x40012008;
    volatile uint32_t *pADC_SQR3 = (volatile uint32_t *)0x40012034;
    volatile uint32_t *pADC_SMPR2 = (volatile uint32_t *)0x4001200C;
    volatile uint32_t *pADC_CR1 = (volatile uint32_t *)0x40012004;

    *pADC_CR2 |= (1 << 0)| (1 << 1);
    *pADC_SQR3 &= ~(0x1FU << 0);
    *pADC_SMPR2 |= (7U << 0);

    // Clearing RES[1:0] (Bits 25:24), AWDSGL (Bit 9), AWDCH[4:0] (Bits 4:0)
        *pADC_CR1 &= ~((3U << 24) | (1U << 9) | (0x1FU << 0));


        // RES = 8-bit (2U << 24)
        // AWDEN = Watchdog Enable (1U << 23)
        // AWDSGL = Single Channel Mode (1U << 9)
        // AWDCH = (Channel 0) 00000
        // AWDIE = Watchdog Interrupt Enable (1U << 6)
        *pADC_CR1 |= (2U << 24) | (1U << 23) | (1U << 9) | (1U << 6);


    // Execution & Data Handling
	volatile uint32_t *pGPIOA_ODR = (volatile uint32_t *)0x40020014;
    volatile uint32_t *pADC_DR = (volatile uint32_t *)0x4001204C;
    volatile uint32_t *pADC_SR = (volatile uint32_t *)0x40012000;

    *pADC_CR2 &= ~(1 << 30);

    // ADC Watch-dog Limit Thresholds
    volatile uint32_t *pADC_HTR = (volatile uint32_t *)0x40012024;
    volatile uint32_t *pADC_LTR = (volatile uint32_t *)0x40012028;


    *pADC_HTR = (200U);
    *pADC_LTR = (50U);




    while(1){

    	if(button_pressed == 1){

    		*pGPIOA_ODR &= ~(1 << 5);
    		*pADC_CR2 |= (1 << 30);


     while( !(*pADC_SR & (1 << 1))) {

    		             }

     volatile uint16_t current_value = *pADC_DR;

     pot_value = update_pot_value(current_value);

    		button_pressed = 0;
    	}

    	/* NOTE: if you get the compilation error of "Target not Responding"
    	 it is because the "__asm volatile ("wfi")" logic causes the CPU to sleep
    	 in real time while uploading your code thus it not responding.

    	 Follow the listed instructions to resolve it;
    	 * Run -> Debug Configurations -> Debugger tab,
    	 *change the "Reset Behaviour" to Connect under reset
  	  	  and click "Debug"	 */

    }
}

    void EXTI15_10_IRQHandler(void){

    	volatile uint32_t *pEXTI_PR = (volatile uint32_t *)0x40013C14;
    	if(*pEXTI_PR & (1 << 13)){

    		*pEXTI_PR = (1 << 13);
    		button_pressed = 1;

    	}
}

    void ADC_IRQHandler(void){
    	 volatile uint32_t *pADC_SR = (volatile uint32_t *)0x40012000;
    	 volatile uint32_t *pGPIOA_ODR = (volatile uint32_t *)0x40020014;

    	 if (*pADC_SR & (1 << 0)){

    		*pGPIOA_ODR |= (1 << 5);
    		*pADC_SR &= ~(1 << 0);

    	}

      }
